package lohr.michael.labyrinth.entities;

/**
 * Created by Michael Lohr on 08.01.2016.
 *
 * a level object, which can be stored in a level file (the ones, generated by the level generator)
 */
public interface ILevelObject {
    int getLevelObjectId();
}
